[project]
name = "simeca-md"
version = "0.1.0"
description = "Converte markdown em docx no formato de um modelo do Word, e o docx em PDF"
requires-python = ">=3.11"
dependencies = []
license = { text = "MIT" }

[project.scripts]
simeca-md = "simeca_md.cli:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["simeca_md"]
